spring:
  application:
    name: itdg-analyzer
  profiles:
    active: local

server:
  port: 8082
  servlet:
    session:
      timeout: 30m
      cookie:
        max-age: 1800

logging:
  level:
    com.itdg: DEBUG